// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

/*
Package helloworld is a generated protocol buffer package.

It is generated from these files:
	helloworld.proto

It has these top-level messages:
	DispatchRequest
	DispatchReply
	HelloRequest
	HelloReply
*/
package helloworld

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// dispatch request messages
type DispatchRequest struct {
	Title string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
}

func (m *DispatchRequest) Reset()                    { *m = DispatchRequest{} }
func (m *DispatchRequest) String() string            { return proto.CompactTextString(m) }
func (*DispatchRequest) ProtoMessage()               {}
func (*DispatchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DispatchRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

// dispatcher response message
type DispatchReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *DispatchReply) Reset()                    { *m = DispatchReply{} }
func (m *DispatchReply) String() string            { return proto.CompactTextString(m) }
func (*DispatchReply) ProtoMessage()               {}
func (*DispatchReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DispatchReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// The request message
type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message
type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*DispatchRequest)(nil), "helloworld.DispatchRequest")
	proto.RegisterType((*DispatchReply)(nil), "helloworld.DispatchReply")
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeter service

type GreeterClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	SayHelloAgain(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SayHelloAgain(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc.Invoke(ctx, "/helloworld.Greeter/SayHelloAgain", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	SayHelloAgain(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SayHelloAgain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHelloAgain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHelloAgain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHelloAgain(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
		{
			MethodName: "SayHelloAgain",
			Handler:    _Greeter_SayHelloAgain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}

// Client API for Dispatcher service

type DispatcherClient interface {
	TestDispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchReply, error)
}

type dispatcherClient struct {
	cc *grpc.ClientConn
}

func NewDispatcherClient(cc *grpc.ClientConn) DispatcherClient {
	return &dispatcherClient{cc}
}

func (c *dispatcherClient) TestDispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchReply, error) {
	out := new(DispatchReply)
	err := grpc.Invoke(ctx, "/helloworld.Dispatcher/TestDispatch", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Dispatcher service

type DispatcherServer interface {
	TestDispatch(context.Context, *DispatchRequest) (*DispatchReply, error)
}

func RegisterDispatcherServer(s *grpc.Server, srv DispatcherServer) {
	s.RegisterService(&_Dispatcher_serviceDesc, srv)
}

func _Dispatcher_TestDispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatcherServer).TestDispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Dispatcher/TestDispatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatcherServer).TestDispatch(ctx, req.(*DispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dispatcher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Dispatcher",
	HandlerType: (*DispatcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestDispatch",
			Handler:    _Dispatcher_TestDispatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0x5d, 0x50, 0xab, 0x8f, 0x96, 0xca, 0x20, 0xb2, 0xb6, 0x17, 0xc9, 0xc1, 0x3f, 0x97,
	0x45, 0xea, 0x5d, 0xb0, 0x0a, 0xf6, 0x58, 0xaa, 0xe8, 0x39, 0xd6, 0x61, 0xbb, 0x90, 0x6d, 0x62,
	0x12, 0xd1, 0xfd, 0x12, 0x7e, 0x66, 0xd9, 0x68, 0x68, 0x90, 0xe2, 0xa1, 0xb7, 0xf9, 0xf3, 0x7b,
	0x6f, 0x92, 0x19, 0x1c, 0x2c, 0x58, 0x29, 0xfd, 0xa1, 0xad, 0x7a, 0x2d, 0x8c, 0xd5, 0x5e, 0x13,
	0x56, 0x15, 0x71, 0x86, 0xfe, 0x5d, 0xe5, 0x8c, 0xf4, 0xf3, 0xc5, 0x8c, 0xdf, 0xde, 0xd9, 0x79,
	0x3a, 0xc4, 0x8e, 0xaf, 0xbc, 0xe2, 0x3c, 0x3b, 0xc9, 0xce, 0xf7, 0x67, 0x3f, 0x89, 0xb8, 0x40,
	0x6f, 0x05, 0x1a, 0xd5, 0x50, 0x8e, 0x4e, 0xcd, 0xce, 0xc9, 0x32, 0x82, 0x31, 0x15, 0x02, 0xdd,
	0x49, 0x3b, 0x21, 0x1a, 0x12, 0xb6, 0x97, 0xb2, 0x8e, 0x58, 0x88, 0xc5, 0x29, 0xf0, 0xcb, 0xfc,
	0xeb, 0x35, 0xfa, 0xca, 0xd0, 0xb9, 0xb7, 0xcc, 0x9e, 0x2d, 0x5d, 0x63, 0xef, 0x41, 0x36, 0x41,
	0x46, 0x79, 0x91, 0x7c, 0x2b, 0x9d, 0x36, 0x38, 0x5a, 0xd3, 0x31, 0xaa, 0x11, 0x5b, 0x74, 0x8b,
	0x5e, 0xd4, 0xdf, 0x94, 0xb2, 0x5a, 0x6e, 0x62, 0x32, 0x7a, 0x02, 0xe2, 0x1e, 0xd8, 0xd2, 0x04,
	0xdd, 0x47, 0x76, 0x3e, 0x56, 0x68, 0x98, 0xea, 0xfe, 0x2c, 0x76, 0x70, 0xbc, 0xbe, 0x19, 0x7c,
	0xc7, 0x97, 0x18, 0x56, 0xba, 0x28, 0xad, 0x99, 0x17, 0xfc, 0x29, 0x6b, 0xa3, 0xd8, 0x25, 0xf8,
	0xb8, 0x1f, 0x1e, 0xf1, 0xdc, 0xc6, 0xd3, 0xf6, 0x88, 0xd3, 0xec, 0x65, 0x37, 0x5c, 0xf3, 0xea,
	0x3b, 0x00, 0x00, 0xff, 0xff, 0x2c, 0xc8, 0xca, 0xf8, 0xe1, 0x01, 0x00, 0x00,
}
