apiVersion: v1
kind: Service
metadata:
  name: default-http-backend
  namespace: ingress-nginx
  labels:
    app: default-http-backend
    kubernetes.io/minikube-addons: ingress
    kubernetes.io/minikube-addons-endpoint: ingress
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001
  selector:
    app: default-http-backend
